name: CI

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
        - { distrib: 'ubuntu', release: '22.04',   codename: 'jammy' }
        - { distrib: 'ubuntu', release: '20.04',   codename: 'focal' }
        - { distrib: 'debian', release: '12-slim', codename: 'bookworm' }
        - { distrib: 'debian', release: '11-slim', codename: 'bullseye' }
    env:
      DISTRIB:  ${{ matrix.distrib }}
      RELEASE:  ${{ matrix.release }}
      CODENAME: ${{ matrix.codename }}
    name: build:${{ matrix.distrib }}:${{ matrix.codename }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup secrets
      run: mkdir -m 0700 secret
    - name: Import GPG passphrase
      run: echo -n "${{ secrets.GPG_PASSPHRASE }}" | base64 -d > secret/passphrase
    - name: Import GPG signing key
      run: echo -n "${{ secrets.GPG_SIGNING_KEY }}" > secret/secret.gpg.asc
    - name: Download source
      run: make download
    - name: Extract archive
      run: make extract
    - name: Build docker
      run: make docker-build
    - name: Build artifact
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.distrib }}-${{ matrix.codename }}
        path: build/target/debian/*.deb
        retention-days: 30
        if-no-files-found: error
  timeline:
    needs: [build]
    name: timeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Timeline
      uses: Kesin11/actions-timeline@v1
