name: CI

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      matrix: ${{ steps.matrix.outputs.targets }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup matrix
      id: matrix
      run: echo "targets=$(make matrix)" >> $GITHUB_OUTPUT
  build:
    needs: [setup]
    strategy:
      matrix:
        target: ${{ fromJson(needs.setup.outputs.matrix) }}
    env:
      DISTRIB:  ${{ matrix.target.distrib }}
      RELEASE:  ${{ matrix.target.release }}
      CODENAME: ${{ matrix.target.codename }}
    name: build:${{ matrix.target.distrib }}:${{ matrix.target.codename }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Make builder
      run: make builder
    - name: Download archive
      run: make download
    - name: Extract archive
      run: make extract
    - name: Build package
      run: make package
    - name: Show sha256sum
      run: cat build/target/debian/SHA256SUMS
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target.distrib }}-${{ matrix.target.codename }}
        path: |
          build/target/debian/SHA256SUMS
          build/target/debian/*.deb
        retention-days: 30
        if-no-files-found: error
  artifacts:
    needs: [build]
    name: artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        path: build/packages
    - name: List packages
      run: ls -lhAR build/packages
    - name: Check sha256sum
      run: |
        cd build/packages
        for d in *; do
          pushd "$d" >/dev/null
          echo -n "$d/"
          sha256sum -c SHA256SUMS
          popd >/dev/null
        done
    - name: Setup secrets
      run: mkdir -m 0700 secret
    - name: Import GPG passphrase
      run: echo -n "${{ secrets.GPG_PASSPHRASE }}" | base64 -d > secret/passphrase
    - name: Import GPG signing key
      run: echo -n "${{ secrets.GPG_SIGNING_KEY }}" | base64 -d > secret/secret.gpg.asc
    - name: Make repository
      run: make repogen
    - name: Sign repository
      run: make reposign
    - name: Generate artifacts
      run: make artifacts
    - name: List artifacts
      run: ls -lhAR public
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: public
        retention-days: 30
        if-no-files-found: error
  timeline:
    needs: [artifacts]
    if: always()
    name: timeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Timeline
      uses: Kesin11/actions-timeline@v1
