name: CI

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
        - { distrib: 'ubuntu', release: '22.04',   codename: 'jammy' }
        - { distrib: 'ubuntu', release: '20.04',   codename: 'focal' }
        - { distrib: 'ubuntu', release: '18.04',   codename: 'bionic' }
        - { distrib: 'ubuntu', release: '16.04',   codename: 'xenial' }
        - { distrib: 'debian', release: '12-slim', codename: 'bookworm' }
        - { distrib: 'debian', release: '11-slim', codename: 'bullseye' }
        - { distrib: 'debian', release: '10-slim', codename: 'buster' }
        - { distrib: 'debian', release: '9-slim',  codename: 'stretch' }
    env:
      DISTRIB:  ${{ matrix.distrib }}
      RELEASE:  ${{ matrix.release }}
      CODENAME: ${{ matrix.codename }}
    name: build:${{ matrix.distrib }}:${{ matrix.codename }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup secrets
      run: mkdir -m 0700 secret
    - name: Import GPG passphrase
      run: echo -n "${{ secrets.GPG_PASSPHRASE }}" | base64 -d > secret/passphrase
    - name: Import GPG signing key
      run: echo -n "${{ secrets.GPG_SIGNING_KEY }}" > secret/secret.gpg.asc
    - name: Build artifact
      run: make
